export default {
  acorn: [[false, true, false, false, false, false, false],
          [false, false, false, true, false, false, false],
          [true, true, false, false, true, true, true]],
  diehard: [[false, false, false, false, false, false, true],
            [true, true, false, false, false,false, false],
            [false, true, false, false, false, true, true, true]],
  glider: [[false, true, false],
           [false, false, true],
           [true, true, true]],
  rPentomino: [[false, true, true],
               [true, true, false],
               [false, true, false]],
  pentadecathlon: [[false, false, true, false, false, false, false, true, false],
                   [true, true, false, true, true, true, true, false, true, true ],
                   [false, false, true, false, false, false, false, true, false]],
  lwss: [[false, true, false, false, true],
         [true, false, false, false, false],
         [true, false, false, false, true],
         [true, true, true, true, false]],
  pulsar: [[false, false, true, true, true, false, false, false, true, true, true, false, false],
           [false, false, false, false, false, false, false, false, false, false, false, false, false],
           [true, false, false, false, false, true, false, true, false, false, false, false, true],
           [true, false, false, false, false, true, false, true, false, false, false, false, true],
           [true, false, false, false, false, true, false, true, false, false, false, false, true],
           [false, false, true, true, true, false, false, false, true, true, true, false, false],
           [false, false, false, false, false, false, false, false, false, false, false, false, false],
           [false, false, true, true, true, false, false, false, true, true, true, false, false],
           [true, false, false, false, false, true, false, true, false, false, false, false, true],
           [true, false, false, false, false, true, false, true, false, false, false, false, true],
           [true, false, false, false, false, true, false, true, false, false, false, false, true],
           [false, false, false, false, false, false, false, false, false, false, false, false, false],
           [false, false, true, true, true, false, false, false, true, true, true, false, false]]
}